name: Deploy to Server

on:

  push:

    branches: [ main ]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3



      - name: Set up SSH

        uses: webfactory/ssh-agent@v0.8.0

        with:

          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}



      - name: Add host to known_hosts

        run: |

          mkdir -p ~/.ssh

          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      

      - name: Deploy with SSH

        run: |

          ssh ${{ secrets.SSH_USER || 'ubuntu' }}@${{ secrets.SSH_HOST }} '

            cd ~/docker-flask-example &&

            git pull &&

            echo "Deployment complete"

          '